// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0H7v57z7vLGgl2AQSWsPr6oIjPX6uaTM',
    appId: '1:741642533514:web:c2012edc7a681766d7cb73',
    messagingSenderId: '741642533514',
    projectId: 'bloombuddy-76127',
    authDomain: 'bloombuddy-76127.firebaseapp.com',
    databaseURL: 'https://bloombuddy-76127-default-rtdb.firebaseio.com',
    storageBucket: 'bloombuddy-76127.appspot.com',
    measurementId: 'G-RKT5VYE7PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3ZQYHO5Bz-p7BCTGWny29Ap_Tc_zZnwI',
    appId: '1:741642533514:android:042252dbb8ed7537d7cb73',
    messagingSenderId: '741642533514',
    projectId: 'bloombuddy-76127',
    databaseURL: 'https://bloombuddy-76127-default-rtdb.firebaseio.com',
    storageBucket: 'bloombuddy-76127.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-Fne0oz3YP4xywiPEwDMujasaazuuPM',
    appId: '1:741642533514:ios:d7c4a22fec43c29dd7cb73',
    messagingSenderId: '741642533514',
    projectId: 'bloombuddy-76127',
    databaseURL: 'https://bloombuddy-76127-default-rtdb.firebaseio.com',
    storageBucket: 'bloombuddy-76127.appspot.com',
    iosBundleId: 'com.example.bloomBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh-Fne0oz3YP4xywiPEwDMujasaazuuPM',
    appId: '1:741642533514:ios:d7c4a22fec43c29dd7cb73',
    messagingSenderId: '741642533514',
    projectId: 'bloombuddy-76127',
    databaseURL: 'https://bloombuddy-76127-default-rtdb.firebaseio.com',
    storageBucket: 'bloombuddy-76127.appspot.com',
    iosBundleId: 'com.example.bloomBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0H7v57z7vLGgl2AQSWsPr6oIjPX6uaTM',
    appId: '1:741642533514:web:2810e5d8590a75bfd7cb73',
    messagingSenderId: '741642533514',
    projectId: 'bloombuddy-76127',
    authDomain: 'bloombuddy-76127.firebaseapp.com',
    databaseURL: 'https://bloombuddy-76127-default-rtdb.firebaseio.com',
    storageBucket: 'bloombuddy-76127.appspot.com',
    measurementId: 'G-4PVNYBY9N8',
  );
}
